name: bnka_challenge
description: bnka Flutter Challenge
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  auth_client:
    path: packages/auth_client
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  string_validator: ^1.1.0
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
