name: auth_client
description: auth_client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  test: ^1.25.7
  mocktail: ^1.0.4
