name: weather_repository
description: weather_repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  open_mateo_api_client:
    path: ../open_mateo_api_client

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  test: ^1.25.7
  mocktail: ^1.0.4
