name: open_mateo_api_client
description: open_mateo_api_client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  dio: ^5.7.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  test: ^1.25.7
  mocktail: ^1.0.4
  http_mock_adapter: ^0.6.1
